In [1]:
# Assignment 0

In [16]:
import pandas as pd
import numpy as np

In [20]:
# Training inputs (image as vector)
X_train = pd.read_csv("data/train_in.csv").to_numpy()

# Training outputs (number that each vector represents)
Y_train = pd.read_csv("data/train_out.csv").to_numpy()

X_test = pd.read_csv("data/test_in.csv").to_numpy()
Y_test = pd.read_csv("data/test_out.csv").to_numpy()

In [44]:
ones = []

for x,y in zip(X_train, Y_train):
    if y == 1:
        ones.append(x)

ones

[array([-1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,  0.51 ,
        -0.213, -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
        -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,  0.292,
         0.792, -0.987, -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
        -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,  0.56 ,
         0.975, -0.873, -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
        -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,  0.745,
         0.999, -0.748, -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
        -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,  0.596,
         1.   , -0.601, -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
        -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,  0.714,
         1.   , -0.585, -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
        -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -0.998,  0.714,
         1.   , -0.454, -1.   , -1.   , -1.   , -1.   , -1.   , 

In [75]:
def get_centroid(X_train):
    sum = np.zeros(X_train.shape[1])
    for x in X_train:
        sum = sum + x
    return sum / X_train.shape[0]


In [74]:
get_centroid(np.array(ones))

(252, 256)


array([-1.        , -1.        , -1.        , -1.        , -1.        ,
       -0.99697222, -0.66161111,  0.51029365,  0.03004365, -0.90127381,
       -0.99891667, -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -0.9820754 , -0.48426587,  0.82638492,  0.71113492,
       -0.60656349, -0.99217857, -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -0.97902778, -0.45460317,  0.86704762,
        0.85275   , -0.48153175, -0.9740873 , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -0.9809246 , -0.44045635,
        0.86792857,  0.88074206, -0.38481746, -0.97134524, -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -0.97

In [79]:
inputs = np.array([
    [5,3],
    [1,6],
    [3,1],
    [2,0],
    [8,5]
])

inputs

array([[5, 3],
       [1, 6],
       [3, 1],
       [2, 0],
       [8, 5]])

In [80]:
get_centroid(inputs)

array([3.8, 3. ])

In [ ]:
label_1_sum = np.zeros((256))
len_1 = 0

for x,y in zip(X_train, Y_train):
    if y == 1:
        label_1_sum = label_1_sum + x
        len_1 = len_1 + 1

print(label_1_sum / len_1)

In [22]:
# list of the centers
clouds = []

for d in range(10):
    # Finding all the indexes from Y_train_out realted to the current d in loop
    d_indexs = np.where(Y_train == d)[0]
    # cloud_d is an array of all images related to the current d
    cloud_d = X_train[d_indexs]
    # Calculating the mean of each cloud
    center_d = np.mean(cloud_d, axis=0)
    # print(center_d)
    # add each mean vector to clouds
    clouds.append(center_d)

print(clouds)

[array([-1.        , -0.99752351, -0.98700313, -0.9459185 , -0.84404389,
       -0.6049906 , -0.14162069,  0.1613605 ,  0.08225078, -0.34288715,
       -0.75336677, -0.93704389, -0.99431661, -0.99962382, -1.        ,
       -1.        , -1.        , -0.99644828, -0.95732288, -0.82737618,
       -0.53845455,  0.01373668,  0.50588088,  0.68423197,  0.64291536,
        0.40327586, -0.04387774, -0.58633229, -0.88969906, -0.98312853,
       -0.99787774, -1.        , -1.        , -0.97439812, -0.85726646,
       -0.60469906, -0.0922069 ,  0.45669906,  0.69878056,  0.68927273,
        0.58257053,  0.55076489,  0.40565831, -0.05483699, -0.55339812,
       -0.87951097, -0.98398433, -0.99711285, -0.99245768, -0.9076395 ,
       -0.68875862, -0.21858934,  0.31976489,  0.62140439,  0.56235737,
        0.27705956,  0.11987461,  0.24439812,  0.41103135,  0.27733542,
       -0.17228213, -0.63031034, -0.91798119, -0.99174608, -0.9644232 ,
       -0.78952978, -0.40848903,  0.08412226,  0.4996489 ,  0.5